language: python
sudo: required
cache: false

services:
  - docker

branches:
  only:
    - master
    - dev

addons:
  apt:
    packages:
    - python-dev
    - python-pip

before_install:
  - printf "[defaults]\nroles_path = /ansible/roles/\n" > ansible.cfg
  - docker pull ubuntu:trusty

install: []

script:
  - docker run -t --rm -v "$TRAVIS_BUILD_DIR:/ansible/roles/onix.openldap:ro" ubuntu:trusty /bin/sh -c "apt-get update && apt-get install -y python-dev python-pip wget curl ca-certificates && pip install ansible==1.9.4 && cd /ansible/roles/onix.openldap && ansible-playbook tests/playbook.yml -i tests/inventory"

notifications:
  email:
    on_success: change
    on_failure: always
