language: python
sudo: required
cache: false

services:
  - docker

branches:
  only:
    - master
    - dev

addons:
  apt:
    packages:
    - python-dev
    - python-pip

before_install:
  - docker pull ubuntu:trusty
  - docker run --name openldap -dit -v "$TRAVIS_BUILD_DIR:/ansible/roles/openldap:ro" ubuntu:trusty

install:
  - docker exec -it openldap /bin/sh -c "apt-get update && apt-get install -y python-dev python-pip wget curl ca-certificates && pip install ansible==1.9.4

script:
  - docker exec -it openldap /ansible/roles/openldap/tests/run-tests.sh

after_script:
  - docker rm -f openldap

notifications:
  email:
    on_success: change
    on_failure: always
