---

- name: cn=config | Generate admin password hash
  command: slappasswd -s {{ openldap_admin_password }} -n
  register: openldap__admin_password_hash
  no_log: true

- name: cn=config | Setting up admin password variable
  set_fact:
    openldap_admin_password_hash: "{{ openldap__admin_password_hash.stdout }}"
  when: openldap_admin_password_hash is not defined

- name: cn=config | Admin password | generating .ldif
  template:
    src: admin_config_pw.ldif.j2
    dest: /tmp/admin_pw.ldif
    owner: root
    group: root
    mode: 0600

- name: cn=config | Admin password | import .ldif
  shell: "ldapmodify -Y external -H ldapi:/// -f /tmp/admin_pw.ldif"

- name: cn=config | Admin password | cleaning up files
  file: path="/tmp/admin_pw.ldif" state=absent
