---

- name: Initial access rules | generating .ldif
  template:
    src: initial_access_rules.ldif.j2
    dest: /tmp/initial_access_rules.ldif
    owner: root
    group: root
    mode: 0600

- name: Initial access rules | import .ldif
  shell: "ldapmodify -Y external -H ldapi:/// -f /tmp/initial_access_rules.ldif"

- name: Initial access rules | cleaning up files
  file: path="/tmp/initial_access_rules.ldif" state=absent
