---

- include_vars: debian.yml
  when: ansible_os_family == "Debian"
  tags: [ openldap, openldap-configure ]

- include: install.debian.yml
  when: ansible_os_family == "Debian"
  tags: [ openldap ]

- include: configure.yml
  tags: [ openldap, openldap-configure ]

- name: Check whether TLS is enabled
  command: ldapsearch -Y external -H ldapi:/// -D "cn=admin,cn=config" -b "cn=config" -LLL "(&(objectClass=olcGlobal)(olcTLSCertificateKeyFile=*))"
  register: openldap__tls_state
  tags: [ openldap, openldap-configure ]

- include: tls-enable.yml
  when: openldap_tls_enable
  tags: [ openldap, openldap-configure ]

- include: tls-disable.yml
  when: not openldap_tls_enable and ("olcTLSCertificateKeyFile" in openldap__tls_state.stdout)
  tags: [ openldap, openldap-configure ]

- name: Check whether initial schema has been imported
  command: ldapsearch -Y external -H ldapi:/// -D "cn=admin,cn=config" -b "cn=config" -LLL "(objectClass=olcMemberOf)"
  register: openldap__memberof_present
  changed_when: 'not ("objectClass: olcMemberOf" in openldap__memberof_present.stdout)'
  tags: [ openldap, openldap-configure ]

- include: memberof.yml
  when: openldap__memberof_present| changed
  tags: [ openldap, openldap-configure ]

- name: Check whether rfc2307bis schema has been imported
  command: ldapsearch -Y external -H ldapi:/// -D "cn=admin,cn=config" -b "cn=config" -LLL "(objectClass=olcSchemaConfig)"
  register: openldap__rfc2307bis_present
  changed_when: 'not ("rfc2307bis" in openldap__rfc2307bis_present.stdout)'
  when: openldap_use_rfc2307bis
  tags: [ openldap, openldap-configure ]

- include: rfc2307bis.yml
  when: openldap_use_rfc2307bis and (openldap__rfc2307bis_present| changed)
  tags: [ openldap ]
