---

- name: MemberOf overlay | generating .ldif
  template:
    src: overlays/memberof.ldif.j2
    dest: /tmp/memberof.ldif
    owner: root
    group: root
    mode: 0600

- name: MemberOf overlay | importing .ldif
  command: ldapadd -Y external -H ldapi:/// -f /tmp/memberof.ldif

- name: MemberOf overlay | removing .ldif
  file: path=/tmp/memberof.ldif state=absent
