---

- name: Initial schema | generating .ldif
  template:
    src: overlays/memberof.ldif.j2
    dest: /tmp/initial_schema.ldif
    owner: root
    group: root
    mode: 0600

- name: Initial schema | importing .ldif
  shell: ldapadd -Y external -H ldapi:/// -f /tmp/initial_schema.ldif && touch {{ openldap_conf_dir }}/{{ openldap_domain }}-schema.populated creates="{{ openldap_conf_dir }}/{{ openldap_domain }}-schema.populated"

- name: Initial schema | removing .ldif
  file: path=/tmp/initial_schema.ldif state=absent
