---

- name: Syncprov overlay | generating .ldif
  template:
    src: overlays/syncprov.ldif.j2
    dest: /tmp/syncprov.ldif
    owner: root
    group: root
    mode: 0600

- name: Syncprov overlay | importing .ldif
  command: ldapadd -Y external -H ldapi:/// -f /tmp/syncprov.ldif

- name: Syncprov overlay | removing .ldif
  file: path=/tmp/syncprov.ldif state=absent
