---

- name: Enabling TLS | Create SSL directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner| default('root') }}"
    group: "{{ item.group| default('root') }}"
    mode: "{{ item.mode| default(omit) }}"
    state: directory
  with_items:
    - { "path": "{{ openldap_tls_cert_dir }}" }
    - { "path": "{{ openldap_tls_private_dir }}", "owner": "{{ openldap_run_user }}", "mode": "0750" }

- name: Copying SSL certificates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode| default('0640') }}"
    owner: "{{ item.owner| default('root') }}"
    group: "{{ item.group| default('root') }}"
  with_items:
    - src: "{{ openldap_tls_local_cacert }}"
      dest: "{{ openldap_tls_cacert }}"
      mode: "0644"
    - src: "{{ openldap_tls_local_server_cert }}"
      dest: "{{ openldap_tls_server_cert }}"
      mode: "0644"
    - src: "{{ openldap_tls_local_server_key }}"
      dest: "{{ openldap_tls_server_key }}"
      mode: "0640"
      owner: "{{ openldap_run_user }}"
      group: "{{ openldap_run_user }}"

- name: Enabling TLS | generating .ldif
  template:
    src: tls_enable.ldif.j2
    dest: /tmp/tls_enable.ldif
    owner: root
    group: root
    mode: 0600

- name: Enabling TLS | import .ldif
  shell: "ldapmodify -Y external -H ldapi:/// -f /tmp/tls_enable.ldif"
  notify: restart openldap

- name: Enabling TLS | cleaning up files
  file: path="/tmp/tls_enable.ldif" state=absent
